# -*- coding: utf-8 -*-
"""function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B_xJL7QJNDEypvmjjWH-az4I34QnMKDG
"""

"""
A function is a block of statements which executes only when it is called somewhere in the program.
"""

#using function to calculate the net worth of ATSMAS

print("ATSMAS Business Net Worth Calculator ")
global company_name
company_name = str(input("Enter Business Name: "))


def Net_Worth  ():

  Total_Assets = int(input("Enter company Total Assets: "))
  Total_Liabilities = int(input("Enter Company Total Liabilities: "))

#net worth calculation
  company_net_Worth = Total_Assets - Total_Liabilities
  return (f"{company_name} Net Worth is : {company_net_Worth}" )

 # Storing all net worth in a list
  company_net_database = [""]
  company_net_database.append( company_net_Worth)
  return company_net_database
Net_Worth ()

#function using the parameters

def salary(hour, rate, tax):
  monthly_net = hour * rate -tax
  name  = input("enter Full Name:")
  return  (f"{name}, your monthly Net Paid is: {monthly_net}")
salary (160, 23, 0.1)