# -*- coding: utf-8 -*-
"""installing_module.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B_xJL7QJNDEypvmjjWH-az4I34QnMKDG
"""

#to install any library or access a module you need to install them
'''
using pip to install : python -m pip install openpyxl
-m : is the module
pip : is the package manager
openpyxl : is the package to install

upgrade pip : python.exe -m pip install --upgrade pip
'''

#accessing the installed module

import openpyxl