# -*- coding: utf-8 -*-
"""medicare_verification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14suT18DTMHM56wh9P7ynjGfTDwLCJ3ek
"""

#Developed: Feb 12, 2024
#name : Mandela Thomas
#building a medicare qualification system

#Medicare qualification incomes
individual_qualified_income =1235.00
married_qualified_income = 1663.00

#user identification and accessing only the last name

user_fullname = str(input("Enter Your Name: "))
last_name = user_fullname.split()[-1]

#user income verification

user_monthly_Household_income = float (input("Enter Household Income $"))

#check whether user meets the qualified income

if  user_monthly_Household_income  <= individual_qualified_income:
  print(f"Congratulations {last_name}, you are qualified for Medicare!")
elif user_monthly_Household_income  > individual_qualified_income:
  print(f"Sorry {last_name}, your monthly household income of {user_monthly_Household_income} is too high!")
else:
  print(f"{last_name}, You might find cheaper healthcare plan on healthcare.gov!")