# -*- coding: utf-8 -*-
"""medicare_verification.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/14suT18DTMHM56wh9P7ynjGfTDwLCJ3ek
"""

#Developed: Feb 12, 2024
#Developer name : Mandela Thomas
#Project name: USA Medicare qualification system

# incomes and age Varification
medicare_age = 60
Medicare_individual_qualified_income =1235.00
Medicare__married_qualified_income = 1663.00

#user verification input
user_fullname = str(input("Enter Your Name: "))
age = int(input("Enter Age: "))

#separating the full name and only take the first name
last_name = user_fullname.split()[-1]

#user income verification
user_monthly_Household_income = float (input("Enter Household Income $"))

#check whether user meets the qualified income

if  user_monthly_Household_income  <= Medicare_individual_qualified_income :
  print(f"Congratulations {last_name}, you are qualified for Medicare!")
elif user_monthly_Household_income  > Medicare_individual_qualified_income :
  print(f"Sorry {last_name}, your monthly household income of {user_monthly_Household_income} is too high!")
else:
  print(f"{last_name}, You might find cheaper healthcare plan on healthcare.gov!")
