# -*- coding: utf-8 -*-
"""module.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B_xJL7QJNDEypvmjjWH-az4I34QnMKDG
"""

"""
In Python, Modules are simply files with the “. py” extension
 containing Python code that can be imported inside another Python Modules Operations Program.
  In simple terms,
we can consider a module to be the same as a code library or a file that contains
 a set of functions that you want to include in your application.

"""


#Modules and importing - Basics
import sys #importing the sys module; the import statements should be placed before any other code in your application

from math import pi #importing only a variable (pi) from the math module

from math import sin #importing only a function (sin()) from the math module; there's no need to add the parantheses of the function when importing it

from math import * #importing all the names (variables and functions) from the math module