# -*- coding: utf-8 -*-
"""nesting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B_xJL7QJNDEypvmjjWH-az4I34QnMKDG
"""

#using for loop nesting

#If / For / While Nesting
x = "Cisco"

if "i" in x:
    if len(x) > 3: #if nesting
        print(x, len(x))




driver_ages = [18, 20, 30, 40, 50]
car_prices = [39000, 50000, 5000, 1000, 12000]

for x in driver_ages:
  for y in car_prices:
    print(x *y)
  print(x)

age = 1


#using while nesting
while age <=10:
  z = 5
  age += 1
  while z <= 10:
    print(z)
    z+=1