# -*- coding: utf-8 -*-
"""variable.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B_xJL7QJNDEypvmjjWH-az4I34QnMKDG
"""

#Knowing about range

"""
What is a variable
In Python, a varibale is a store container. One that store the value in memory.

"""
#Declaring a variable
name = ""

#assigning a variable
name = "Mandela Philip Thomas"

#adding multiple variables and newline

name, major, school = "Mandela Thomas", "PHD in healthcare Management & Economics ", "Wharton University of Pennsylvania"
print(f"{name} is majoring in {major} \n at the {school} located Pennsylvania")

#reassigning a variable
forname = "mandela philip Thomas"
fname = "Philip mandela Thomas"
print(fname)